### ISSUE TITLE
session/get-in returns nil in place of false

### ISSUE THREAD

**Issue by jmromrell** [reagent-project/reagent-utils#14]
```
(session/put! "data" {"a" true "b" false "c" nil})
(session/get-in ["data" "a"]) ;returns true
(session/get-in ["data" "b"]) ;returns nil
(session/get-in ["data" "c"]) ;returns nil
(session/get-in ["data" "d"]) ;returns nil
```
There is no way to differentiate between cases b (key exists and is associated with false), c (key exists and is associated with nil), and d (key does not exist).

I would expect case b to return false, case c to return nil, and case d to return default argument (defaults to nil).

**Comment by yogthos** [comment]
Hi,

You're right that's a bug, the implementation was using an `or` with the session value and the default value, so when session value was `false` it would return the default which is `nil`. Just pushed out `0.3.2` with a fix.
