### ISSUE TITLE
goog.net.cookies API has changed

### ISSUE THREAD

**Issue by axrs** [reagent-project/reagent-utils#17]
https://google.github.io/closure-library/api/goog.net.cookies.html

Especially the `.set` API which now takes an option map instead of individual option arguments.

**Comment by yogthos** [comment]
any chance of a pr to get the API updated? :)

**Comment by axrs** [comment]
Sure is. I'll look at doing one up tonight

**Comment by yogthos** [comment]
awesome, thanks a lot and I can do a release any time
