### ISSUE TITLE
Use SetOptions interface when setting cookie options

### ISSUE THREAD

**Issue by alvinfrancis** [reagent-project/reagent-utils#20]
Likely related to some issues raised in the discussion around https://github.com/reagent-project/reagent-utils/issues/19.  For example this comment: https://github.com/reagent-project/reagent-utils/issues/19#issuecomment-968342459

I also had issues where `max-age` was not being applied on later versions of GCL even with proper dependencies applied for shadow-cljs.  Found this [relevant discussion](https://clojurians-log.clojureverse.org/clojurescript/2021-05-12/1620834892.357300) on goog.net.cookies options usage where another person had the same issue with max-age.  Apparently, passing options as JSON when setting cookies is insufficient as is currently done here:

https://github.com/reagent-project/reagent-utils/blob/30947c452ed12ef68dd6e235634d108cc9e7f841/src/reagent/cookies.cljs#L41-L48

Instead, the passed options object should support the `goog.net.Cookies.SetOptions` interface, either by creating a `deftype` with the same fields, or using `SetOptions` directly as mentioned in the linked discussion.  In our case, we dropped to using GCL directly and either solution managed to resolve the issue with options not being properly applied in production builds.

**Comment by yogthos** [comment]
Thanks for the heads up, could you try see if [this commit](https://github.com/reagent-project/reagent-utils/commit/27edbb0ed08cdc8b49742c21fa6d25f2b11e98bf) works on your end?

**Comment by alvinfrancis** [comment]
> Thanks for the heads up, could you try see if [this commit](https://github.com/reagent-project/reagent-utils/commit/27edbb0ed08cdc8b49742c21fa6d25f2b11e98bf) works on your end?

Quick check using that commit and yes that indeed works :+1:
