### ISSUE TITLE
cookies.cljs depends on deleted goog.net.cookies

### ISSUE THREAD

**Issue by scarytom** [reagent-project/reagent-utils#21]
We upgraded from shadow-cljs 2.21.0 -> 2.22.0 today and started getting the following error:
```The required namespace "goog.net.cookies" is not available, it was required by "reagent/cookies.cljs".```

Turns out one of the shadow-cljs changes was to [bump the google-clojure-library](https://github.com/thheller/shadow-cljs/commit/5168aff39ddb21ddc5f6e18828456cc73c216e65) from an astonishly ancient v20211011 to a pretty recent v20230227.

Amongst the vast number of GCL releases between those two was [v20220301](https://github.com/google/closure-library/releases/tag/v20220301), which included a change to ["Delete deprecated goog.net.cookies"](https://github.com/google/closure-library/commit/67d06cf7b73c3e228916218c12a500c7c930c880). The message for that change states:
> goog.net.cookies was deprecated and replaced by goog.net.Cookies some time ago.

So, we now move our attention to the [reagent-utils](https://github.com/reagent-project/reagent-utils) lib, and specifically the [cookies.cljs](https://github.com/reagent-project/reagent-utils/blob/master/src/reagent/cookies.cljs) namespace.  That require of `goog.net.cookies` seems suspicious, especially considering `goog.net.Cookies` is required on the line below.

This issue has been discussed on the [Clojurians Slack](https://clojurians.slack.com/archives/C0620C0C8/p1678379726699909) instance.

I plan on putting a pull-request together that fixes this issue.  Please let me know if I'm wasting my time doing that.

**Comment by yogthos** [comment]
Hi thanks for the heads up, and a PR would be appreciated. I can do a release for the library once we get it merged in.

**Comment by scarytom** [comment]
Let me know what you think of that pull request: I'm happy to make further changes.

**Comment by yogthos** [comment]
Thanks, the change looks good to me. It's pretty straight forward. I just pushed out `0.3.6` with the fix.
