### ISSUE TITLE
Cursors for more efficient rendering

### ISSUE THREAD

**Issue by Frozenlock** [reagent-project/reagent-utils#5]
I think this could be made more efficient by using cursors.
As explained in [News in 0.6.0](http://reagent-project.github.io/news/news060-alpha.html) (very bottom):

> Cursors are now cached, which should make them a bit easier to use. Previously, every instance of cursor had its own state. Now cursors called with the same arguments share data (...)

Thus, we could do the following and avoid re-rendering (or at least checking for changes) when only a subset of the state atom is changed:

```clj
(defn get
  "Get the key's value from the session, returns nil if it doesn't exist."
  [k & [default]]
  (let [temp-a (reagent/cursor state [k])]
    (or @temp-a default)))
```

Thoughts?

**Comment by yogthos** [comment]
Yeah I think that's a great idea.

**Comment by Frozenlock** [comment]
Good.

I'll try to do a PR tonight.

**Comment by yogthos** [comment]
awesome!

**Comment by yogthos** [comment]
ok got my keys setup and it's up on Clojars :)

**Comment by yogthos** [comment]
if everything looks good we can close this one
